- name: Configure Shipping Componant
  hosts: shipping
  become: yes

# 1. Record the exact start time before any work begins
  pre_tasks:
    - name: Record playbook start time
      ansible.builtin.set_fact:
        playbook_start_time: "{{ now(utc=true).strftime('%s') }}"

  tasks:
  - name: Install Maven and MySQL
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - maven
    - mysql

  - name: Install PyMySQL and cryptography
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: Download Shipping Code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Extract shipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Install Maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Rename Jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: Copy Shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  # - name: Connect to MySQL server using app user
  #   community.mysql.mysql_info:
  #     login_user: shipping
  #     login_password: RoboShop@1
  #     login_hosts: mysql.arohvya.online
  #     login_db: cities
  
  - name: Import data
    tags: # To run this particular task we can use #tags option, To run this one in terminal in the end use -t and the tag name import -t import
    - import 
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.arohvya.online
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: Restart Shipping
    tags:
    - restart
    ansible.builtin.service:
      state: restarted
      name: shipping



# 2. Run this at the very end to calculate and display the total duration
  post_tasks:
    - name: Display total execution time
      vars:
        playbook_end_time: "{{ now(utc=true).strftime('%s') }}"
      ansible.builtin.debug:
        msg: "Total playbook execution time: {{ (playbook_end_time | int) - (playbook_start_time | int) }} seconds."