[mongodb]
mongodb.arohvya.online

[catalogue]
catalogue.arohvya.online

[frontend]
frontend.arohvya.online

[redis]
redis.arohvya.online

[user]

[cart]

[mysql]

[shipping]

[rabbitmq]

[payment]

[dispatch]
