[mongodb]
mongodb.arohvya.online

[catalogue]
catalogue.arohvya.online

[frontend]
frontend.arohvya.online

[redis]
redis.arohvya.online

[user]
user.arohvya.online

[cart]
cart.arohvya.online

[mysql]

[shipping]

[rabbitmq]

[payment]

[dispatch]
